{
 "title": "Hypervolt Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "charger_id", "label": "Charger ID", "query": { "query": "hypervolt_charger_info" } }
  ]
 },
 "panels": [
  {
   "title": "Charging",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hypervolt_charger_charging{charger_id=\"$charger_id\"}"
    }
   ]
  },
  {
   "title": "Charging Schedule",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hypervolt_charger_schedule_enabled{charger_id=\"$charger_id\"}"
    }
   ]
  },
  {
   "title": "LED Brightness",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nhypervolt_charger_led_brightness_percentage{charger_id=\"$charger_id\"}"
    }
   ]
  },
  {
   "title": "Watt Hours Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hypervolt_charger_charge_watt_hours{charger_id=\"$charger_id\"}"
    }
   ]
  },
  {
   "title": "Carbon Saved",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hypervolt_charger_charge_carbon_saved_grams{charger_id=\"$charger_id\"}"
    }
   ]
  },
  {
   "title": "Spent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hypervolt_charger_charge_ccy_spent{charger_id=\"$charger_id\"}/100"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "hypervolt_charger_max_current_milliamps{charger_id=~\"$charger_id\"}",
     "legendFormat": "Max Charge  Current"
    },
    {
     "expr": "hypervolt_charger_ct_current_milliamps{charger_id=~\"$charger_id\"}",
     "legendFormat": "CT Current"
    },
    {
     "expr": "hypervolt_charger_charge_current_milliamps{charger_id=~\"$charger_id\"}",
     "legendFormat": "Charge Current"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "hypervolt_charger_ct_voltage_volts{charger_id=\"$charger_id\"}",
     "legendFormat": "CT Voltage"
    }
   ]
  }
 ]
}